### ISSUE TITLE
可以顺便修复一下 v2rayhelper 占用资源100%的问题嘛？

### ISSUE THREAD

**Issue by Elvis-Zhou** [kanyways/V2rayU#1]
可以顺便修复一下 v2rayhelper 占用资源100%的问题嘛？

**Comment by kanyways** [comment]
> 可以顺便修复一下 v2rayhelper 占用资源100%的问题嘛？

我应该怎么说呢？我其实不会IOS开发，哈哈哈，掩面泪奔。

**Comment by kanyways** [comment]
另外我刚才监控自己的电脑没有发现有这个问题，

- Mac OS：10.15.4
- Mac Book Pro：2012 mid
- 内存：8G
- CPU：2.3GHz  4 Core i7

**Comment by kanyways** [comment]
兄弟，作者说修复了，我同步了相关的更新。
